### ISSUE TITLE
compare to euBusinessGraph NUTS/LAU

### ISSUE THREAD

**Issue by VladimirAlexiev** [SEMICeu/NUTS_pilot#2]
The euBusinessGraph project uses https://github.com/euBusinessGraph/eubg-data/blob/master/data/neogeo-nuts-0.91.ttl.
- We've extended it for Montenegro: https://github.com/euBusinessGraph/eubg-data/blob/master/data/neogeo-nuts-ME.ttl
- More importantly, we created RDF for LAU1,2 (formerly known as NUTS4,5): https://github.com/euBusinessGraph/eubg-data/tree/master/data/LAU

Does this project cover LAU or only NUTS1,2,3?
Is there some official recommendation about NUTS URLs, or we should continue using Neogeo NUTS?

cc @patzomir, @elvesater

**Comment by bertvannuffelen** [comment]
closed because the repository is archived.
